src/components/ClaimFilter.js
src/translations/en.json

TICKET: [OAI-36](https://openimis.atlassian.net/browse/OAI-36)

OAI-36: Moved medical filters to claim module

---

src/components/ClaimSearcher.js
src/reducer.js

TICKET: [OAI-45](https://openimis.atlassian.net/browse/OAI-45)

OAI-45: Remove duplicates from claim search

---

src/components/ClaimChildPanel.js
src/pages/HealthFacilitiesPage.js

TICKET: [OP-974](https://openimis.atlassian.net/browse/OP-974)

OP-974: Submitting review fixed

---

src/actions.js
src/components/ClaimMasterPanel.js

https://openimis.atlassian.net/browse/OP-1030

OP-1030: modular IMIS:  the field Adjusted remains blank

---

src/components/ClaimChildPanel.js
src/components/ClaimSearcher.js
src/translations/en.json

https://openimis.atlassian.net/browse/OP-1031

OP-1031: modular IMIS:missing field Valuation

---

src/actions.js
src/components/ClaimFilter.js
src/components/ClaimForm.js
src/components/ClaimMasterPanel.js
src/reducer.js
src/translations/en.json

Ticket:
https://openimis.atlassian.net/browse/OP-1081
Changes:
- implemented ValidatedTextInput for Claim Code
- clearing claim after leaving edit claim form
- validating field
- deleted old approach for claim code validation
BE PR:
https://github.com/openimis/openimis-be-claim_py/pull/70

Feature/op 1081: claim code validation

---

src/actions.js
src/components/ClaimFilter.js
src/pickers/ClaimAdminPicker.js

[OTC-945](https://openimis.atlassian.net/browse/OTC-945)
Changes:
- Now, if user is attached to the HF, CA list is adjusted to that location restriction.
[OTC-945]: https://openimis.atlassian.net/browse/OTC-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-945: Adjust CA list when user has a location restrictions

---

src/components/ClaimMasterPanel.js

[OTC-946](https://openimis.atlassian.net/browse/OTC-946)
Changes:
- I restricted claim code to be max 8 chars long. It was already implemented, I just passed inputProps to the component.
[OTC-946]: https://openimis.atlassian.net/browse/OTC-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-946: Claim code length restriction

---

src/components/ClaimForm.js

https://openimis.atlassian.net/browse/OTC-966

OTC-966: make save button always visible

---

src/components/ClaimSearcher.js

https://openimis.atlassian.net/browse/OTC-1000
This PR fixes summing claim and approved amounts of selected claims.

OTC-1000: fix sum of selected claims

---

src/components/ClaimForm.js
src/pickers/ClaimAdminPicker.js

https://openimis.atlassian.net/browse/OTC-1008
It is also a part of: https://github.com/openimis/openimis-be-claim_py/pull/88

OTC-1008: use just one query to fetch claim admins

---

src/components/ClaimChildPanel.js

https://openimis.atlassian.net/browse/OP-1310
After this PR using decimals in price in claim will be possible.
It needs this PR to work: https://github.com/openimis/openimis-fe-core_js/pull/111

OP-1310: allow decimals in price

---

src/components/ClaimForm.js

https://openimis.atlassian.net/browse/OP-1337
This PR allows to create claim even after refreshing a page.

OP-1337: when refreshing a page on active claim save hf and admin data

---

src/components/ClaimFilter.js

Ticket:
https://openimis.atlassian.net/browse/OP-1338
Changes:
- marked CA field as required, without it you cannot create Claim. User should be informed

OP-1338: marked CA field as required to create claim

---

src/actions.js
src/components/ClaimForm.js
src/components/ClaimMasterPanelExt.js
src/reducer.js
src/translations/en.json

https://openimis.atlassian.net/browse/OP-1324
It requires backend PR: https://github.com/openimis/openimis-be-claim_py/pull/91

OP-1324: change filtering of a last claim in the query

---

src/pickers/ClaimAdminPicker.js
src/reducer.js

Ticket:
https://openimis.atlassian.net/browse/OP-1342
Changes:
- if user has HF attached to the account it will be passed to CA picker

OP-1342: user health facility is passed to claim admin picker

---

src/index.js
src/reports/ClaimPercentageReferralsReport.js
src/translations/en.json

Added a new report for claim percentage referrals.
Ticket: [https://openimis.atlassian.net/browse/OMT-313](https://openimis.atlassian.net/browse/OMT-313)

OMT-313: Claim percentage referrals report

---

src/actions.js
src/components/ClaimChildPanel.js
src/components/ClaimFilter.js
src/components/ClaimForm.js
src/components/ClaimMasterPanel.js
src/components/ClaimMasterPanelExt.js
src/components/ClaimSearcher.js
src/constants.js
src/index.js
src/pages/HealthFacilitiesPage.js
src/pages/ReviewsPage.js
src/pickers/ClaimAdminPicker.js
src/reducer.js
src/reports/ClaimPercentageReferralsReport.js
src/translations/en.json

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

src/components/ClaimFilter.js

[OTC-1084](https://openimis.atlassian.net/browse/OTC-1084)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
[OTC-1084]: https://openimis.atlassian.net/browse/OTC-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OTC-1084: fix resetting search criteria in claim module

---

README.md
src/actions.js
src/components/ClaimForm.js
src/components/ClaimMasterPanel.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/ONI-72
Changes:
- Added basic logic for new field - referal HF 
- Added description for new config in readme

ONI-72: Basic referal logic in claim form.

---

src/translations/en.json

Fix en.json file syntax to fix the compilation process of the claim module.

Fix en.json

---

src/components/ClaimMasterPanel.js

Revert this since it's causing error while saving claim.

Revert "OTC-1108: insuree picker type changed"

---

README.md

Ticket: https://openimis.atlassian.net/jira/software/c/projects/ONI/issues/ONI-126
Changes:
- Spelling corrected.
- Added docs for two configuration options.

ONI-126: Missing docs added.

---

src/components/ClaimChildPanel.js

Ticket: https://openimis.atlassian.net/browse/ONI-128
Changes:
- Items/services dropdown fix.

ONI-128: Claim items/services fix.

---

src/components/ClaimChildPanel.js

Ticket: https://openimis.atlassian.net/browse/ONI-67
Changes:
- Added filter to the item/service picker.
- Items/services already picked will be filtered out and could not be selected again.

ONI-67: Block service/item already entered.

---

src/actions.js
src/components/ClaimForm.js

Ticket: https://openimis.atlassian.net/browse/ONI-69
Dependencies:
BE Medical PR: https://github.com/openimis/openimis-be-medical_py/pull/41
FE Medical PR: https://github.com/openimis/openimis-fe-medical_js/pull/50
Changes:
- Check for maximum amount of item/service
- Block them if maximum amount overshoot

ONI-69: Blocking claims with items/services above maximum threshold.

---

src/components/ClaimChildPanel.js
src/components/ClaimForm.js

Ticket: https://openimis.atlassian.net/browse/ONI-83
Changes:
- Saving a review is blocked if user tries to increase item/service quantity above original value
- Warning is shown under this field

ONI-83: Prevent increase of item/service quantity during review.

---

README.md

Ticket: https://openimis.atlassian.net/browse/ONI-90
Changes:
- Added missing docs.

ONI-90: Added missing docs about default claim review filters.

---

src/actions.js

Ticket: https://openimis.atlassian.net/browse/ONI-132
Related PR's:
https://github.com/openimis/openimis-be-core_py/pull/206
https://github.com/openimis/openimis-be-claim_py/pull/123
Changes:
- Changed GQL argument name to fit backend solution

ONI-132: Changed GQL variable name for autogeneration.

---

src/actions.js

Ticket: https://openimis.atlassian.net/browse/ONI-141
Changes:
- Fixed editing claim with autogeneration of code.
- Claim code will no longer be overwritten.

ONI-141: Editing claim code with autogeneration fix.

---

README.md
src/components/ClaimChildPanel.js
src/components/ClaimSearcher.js

Ticket: https://openimis.atlassian.net/browse/ONI-143
Required PR: https://github.com/openimis/openimis-fe-core_js/pull/146
Changes:
- Show ordinal number column in claims and items/services of a given claim.

ONI-143: Optional number column enabled.

---

src/components/ClaimMasterPanel.js
src/constants.js

https://openimis.atlassian.net/browse/OP-1489
This PR displays adjusted price as:  SUM ( coalease( item_service.ADJUSTED, item_service.price_appoved,item_service.price_ASKED)  *  coalease(  item_service.qty_appoved,item_service.qty_ASKED)  )

OP-1489: fix adjusted price

---

src/components/ClaimSearcher.js

[OP-1513](https://openimis.atlassian.net/browse/OP-1513)
Changes:
- Display 0 when count is not defined (prevent calling .toString method on undefined).
[OP-1513]: https://openimis.atlassian.net/browse/OP-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1513: display 0 when count is not defined

---

src/components/ClaimForm.js
src/constants.js

[OP-1541](https://openimis.atlassian.net/browse/OP-1541)
Changes:
-  Resetting of relevant keys instead of removing all storage. This will ensure leaving the rest of the localStorage intact.
[OP-1541]: https://openimis.atlassian.net/browse/OP-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1541: fix clearing local storage

---

src/components/ClaimInsureeSummary.js

[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
Change:
- Hide 'Create claim' button in top right corner.
- Disable 'View' button when user is not permitted.
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ONI-95: hide add claim button

---

src/components/ClaimFilter.js
src/components/ClaimMasterPanelExt.js
src/pages/ReviewsPage.js
src/translations/en.json

MERGING RELEASE branches
Release release/23.10

MERGING develop into release/23.10

---

README.md
src/components/ClaimForm.js
src/components/ClaimMasterPanel.js

Ticket: https://openimis.atlassian.net/browse/OP-1689
Changes:
- Refer HF now present in every form
- No longer mandatory for everyone, can be set mandatory with setting

OP-1689: Change refer HF to not be mandatory.

---

src/components/ClaimForm.js

[OP-1723](https://openimis.atlassian.net/browse/OP-1723)
Changes:
- Add lockedPage styles when claim saved.
- Adjust reload.
[OP-1723]: https://openimis.atlassian.net/browse/OP-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1723: add lockedpage styles, adjust reload

---

src/actions.js
src/components/ClaimForm.js
src/components/ClaimMasterPanel.js
src/pages/EditPage.js
src/translations/en.json

Ticket: https://openimis.atlassian.net/browse/OP-1779
Changes:
- Added condition to stop autogeneration if claim is restored

OP-1779: Do not autogenerate claim code if claim is restored.

---

src/components/ClaimChildPanel.js
src/components/ClaimForm.js
src/translations/en.json

[OP-1827](https://openimis.atlassian.net/browse/OP-1827)
Changes:
- Add check that quantity has to be greater than 0.
[OP-1827]: https://openimis.atlassian.net/browse/OP-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1827: quantity has to be greater than 0

---

src/actions.js

REQUIRES: https://github.com/openimis/openimis-be-claim_py/pull/166

avoid claim auto join to get the restore.id

---

src/components/ClaimMasterPanelExt.js
src/constants.js

[OP-1792](https://openimis.atlassian.net/browse/OP-1792)
Changes:
- Include Policy status when evaluating policy validity.
[OP-1792]: https://openimis.atlassian.net/browse/OP-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1792: include status when evaluating policy

---

src/components/ClaimMasterPanelExt.js
src/constants.js

MERGING develop into release/24.04

MERGING develop into release/24.04

---

src/components/ClaimForm.js

[OP-1899](https://openimis.atlassian.net/browse/OP-1899)
Changes:
- If the user has the authority to submit a claim review, the system will now display the 'Deliver review' submit button.
[OP-1899]: https://openimis.atlassian.net/browse/OP-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1899: change right to review claim
