src/components/ClaimSearcher.js
Required for [OAI-42](https://openimis.atlassian.net/browse/OAI-42). Field "was_categorized" is nested and previous solution didn't allow displaying the value. Currently the configuration can include all fields present in json_ext, also nested and present in the list of values.
=> OAI-42: Change function for fetching data from json_ext 

src/components/ClaimSearcher.js
I've removed the blank line when there are no items selected.
=> fix: Remove pre-headers row when not needed

src/components/ClaimFilter.js, src/pickers/ClaimAdminPicker.js
Ticket:
https://openimis.atlassian.net/browse/OP-1041
Changes:
- extended ClaimAdminPicker and ClaimFilter to pass user's related HF that is required on the backend filtering
Related PR:
https://github.com/openimis/openimis-be-claim_py/pull/65
=> OP-1041: extended claim admin query with user's related HF

src/actions.js, src/components/ClaimFilter.js, src/pickers/ClaimAdminPicker.js, src/reducer.js
Ticket:
https://openimis.atlassian.net/browse/OP-1086
Changes:
- added fetching available HF to Claim Admin Picker. HFs are filtered by available location.
- state is extended with 'healthFacilities'
Notes:
- double use of 'useEffect' may require refactor
Realted:
https://github.com/openimis/openimis-be-location_py/pull/49
https://github.com/openimis/openimis-be-claim_py/pull/68
=> Feature/op 1086: filter for claim admins 

src/components/ClaimForm.js
Extending the Claim Form was not passing the claim UUID or details, so I added most fields from the main Form to the contribution.
=> ClaimForm should pass Claim info

src/components/ClaimChildPanel.js
https://openimis.atlassian.net/browse/OP-1307
This PR blocks editing of item service status in claim.
=> OP-1307: make status picker always read only in claim detail

src/components/ClaimMasterPanel.js
**REQUIRED [INSUREE PR](https://github.com/openimis/openimis-fe-insuree_js/pull/65)**
**REQUIRED [BE PR](https://github.com/openimis/openimis-be-claim_py/pull/105)**
[OTC-1108](https://openimis.atlassian.net/browse/OTC-1108)
Changes:
- Use _InsureeNameByChfIdPicker_ instead of _InsureeChfIdPicker_.
[OTC-1108]: https://openimis.atlassian.net/browse/OTC-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OTC-1108: insuree picker type changed

src/components/ClaimChildPanel.js
Ticket: https://openimis.atlassian.net/browse/ONI-82
Changes:
- Moved button code inside an if function
- Now buttons will not be rendered in the new claim form.
Screenshot of the bug:
=> ONI-82: Button display fix.

src/components/ClaimMasterPanelExt.js, src/translations/en.json
Ticket: https://openimis.atlassian.net/browse/ONI-64
Required PR's: 
https://github.com/openimis/openimis-fe-core_js/pull/140
Changes:
- Changing label of policy section depending on its active/inactive status
- Color is changed as well
=> ONI-64: Policy active/inactive status indicator.

src/actions.js, src/components/ClaimChildPanel.js
[OP-1491](https://openimis.atlassian.net/browse/OP-1491)
Changes:
- Claim item and service status cannot be changed during review only if product in item/service is not defined.
[OP-1491]: https://openimis.atlassian.net/browse/OP-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1491: make status picker disabled if product id not defined

src/components/ClaimFilter.js
[OP-1454](https://openimis.atlassian.net/browse/OP-1454)
Changes:
- Parse ‘Claimed More/Less Than’ to decimal before sending filters.
[OP-1454]: https://openimis.atlassian.net/browse/OP-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1454: parse to decimal before sending filters to query

README.md, src/components/ClaimMasterPanel.js
Ticket: https://openimis.atlassian.net/browse/ONI-146
Changes:
- Default value of date claimed set to current date
- Added setting to make this field read only, allowing only current date as date of new claims.
=> ONI-146: Claimed date set to current date setting.

src/components/ClaimChildPanel.js
Ticket: https://openimis.atlassian.net/browse/ONI-151
Changes:
- Reject/accept all buttons are now only rendered for claim in 'checked' status.
- They are only rendered if there are any services/items in given claim.
=> ONI-151: Additional conditions for reject/accept all rendering.

src/components/ClaimInsureeSummary.js, src/index.js
[ONI-95](https://openimis.atlassian.net/browse/ONI-95)
[RELATED PR #1](https://github.com/openimis/openimis-fe-policy_js/pull/62)
[RELATED PR #2](https://github.com/openimis/openimis-fe-insuree_js/pull/90)
Changes:
- Add component which displays claim related to provided insuree.
[ONI-95]: https://openimis.atlassian.net/browse/ONI-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ONI-95: table with claims related to insuree

src/components/ClaimSearcher.js
TICKET: https://openimis.atlassian.net/browse/CQI-95
EXPLANATION:
The error related to the Department of Defense (DoD) might be due to the usage of a regular expression that is potentially vulnerable to super-linear runtime and backtracking, which could lead to performance issues or even denial of service in certain cases. The DoD might have strict security guidelines in place, and using regular expressions with these characteristics could be considered a security risk.
The issue with the regular expression is the use of the \B assertion, which asserts a position where there's no word boundary. This can lead to backtracking, especially in cases where the input string is large, potentially resulting in poor performance.
To fix this issue and satisfy DoD requirements, we used a more …
=> CQI-95: fixed issue with regex hotspot security OWASP Injection

src/components/ClaimFilter.js, src/components/ClaimSearcher.js
[OP-1705](https://openimis.atlassian.net/browse/OP-1705)
Changes:
- Adjusted the "Visit Date From" and "Visit Date To" fields to function accurately as a date range filter, ensuring they search within the specified timeframe rather than targeting the exact dates provided.
- Quick fix on sorting if oridinal number column is visible.
[OP-1705]: https://openimis.atlassian.net/browse/OP-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1705: fix visit date filters

src/components/ClaimMasterPanel.js
[OP-1725](https://openimis.atlassian.net/browse/OP-1725)
Changes:
- Remove the 'none/null' option from the dropdown menu in the form.
[OP-1725]: https://openimis.atlassian.net/browse/OP-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1725: remove null/empty option from dropdown

src/components/ClaimChildPanel.js
[ONI-134](https://openimis.atlassian.net/browse/ONI-134)
[REQUIRED PR](https://github.com/openimis/openimis-fe-core_js/pull/190)
Changes:
- Enhance the Services/Items Table by appending extra information to the headers.
[ONI-134]: https://openimis.atlassian.net/browse/ONI-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ONI-134: add info about items/services to the table header

src/components/ClaimForm.js, src/components/ClaimMasterPanel.js, src/translations/en.json
[OP-1759](https://openimis.atlassian.net/browse/OP-1759)
[REQUIRED](https://github.com/openimis/openimis-fe-core_js/pull/195)
Changes:
- New button to add new claim after form saving.
- Clear the form when button clicked and allow to fill and save again.
Demo:
[OP-1759]: https://openimis.atlassian.net/browse/OP-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1759: add button to add new claim after save

src/components/ClaimChildPanel.js
[OP-1829](https://openimis.atlassian.net/browse/OP-1829)
[REQUIRED](https://github.com/openimis/openimis-fe-core_js/pull/202)
Changes:
- Disable the delete button on empty row in claim services/items table.
[OP-1829]: https://openimis.atlassian.net/browse/OP-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1829: disable delete button on empty row

src/components/ClaimForm.js
[OP-1830](https://openimis.atlassian.net/browse/OP-1830)
[REQUIRED](https://github.com/openimis/openimis-fe-core_js/pull/203)
Changes:
- Saving disabled if price of service/item < 0.
- Complexity of `canSaveDetail` has been reduced.
[OP-1830]: https://openimis.atlassian.net/browse/OP-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1830: price of service/item could not be negative
